In [1]:
import cv2
from keras.models import load_model
import numpy as np
import time
import camera_rps
choice_list = ['rock', 'paper', 'scissors']
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
started= False
next_round=True
countdown=False
counter=0
elapsed=0
round_time=0

message=''
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    if not started:
        message ='Press a to start'
    if cv2.waitKey(33)==ord('a'):
        if not started:
            counter=time.time()
            started=True
            countdown=True
    if started:
        elapsed=5-(time.time()-counter)
        if elapsed <= -3:
            message='Press n to play the next round'
            if cv2.waitKey(33)==ord('n'):
                started =False
                elapsed=0
        elif elapsed<=0:
            countdown= False
            prediction=camera_rps.get_prediction(data)
            computer_choice=camera_rps.get_computer_choice(choice_list)
            message =f'Your choice is{prediction},computer is{computer_choice}'
            winner=camera_rps.who_won(prediction,computer_choice)
            message =f'{winner}'
        if countdown:
            message=f'Show your hand in{int(elapsed)} seconds'

    cv2.putText(frame,message,(30,30),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),1)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()



1/1 [==============================] - 1s 729ms/step
[[4.3375997e-04 9.9370354e-01 1.3242015e-03 4.5385598e-03]]
1/1 [==============================] - 0s 27ms/step
[[0.00134025 0.08717075 0.01049293 0.9009961 ]]
1/1 [==============================] - 0s 32ms/step
[[0.0012398  0.1615356  0.01505503 0.8221696 ]]
1/1 [==============================] - 0s 28ms/step
[[2.5538917e-04 2.4637613e-03 2.4214931e-04 9.9703872e-01]]
1/1 [==============================] - 0s 25ms/step
[[9.6206518e-04 1.1238836e-02 1.2800955e-03 9.8651892e-01]]
1/1 [==============================] - 0s 25ms/step
[[5.2982586e-04 8.0086244e-03 2.9909651e-04 9.9116242e-01]]
1/1 [==============================] - 0s 29ms/step
[[8.8582083e-04 2.1589240e-03 2.7123906e-04 9.9668401e-01]]
1/1 [==============================] - 0s 28ms/step
[[3.3346601e-04 1.7682730e-03 3.3628338e-04 9.9756193e-01]]
1/1 [==============================] - 0s 28ms/step
[[2.5591996e-04 7.9831118e-03 2.1343837e-04 9.9154752e-01]]
1/1 [==========

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

: 