In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()


1/1 [==============================] - 1s 926ms/step
[[0.23162144 0.06664635 0.01001721 0.69171494]]
1/1 [==============================] - 0s 25ms/step
[[0.01618508 0.00979092 0.00185391 0.9721701 ]]
1/1 [==============================] - 0s 24ms/step
[[6.1944714e-03 4.1383035e-03 7.0344209e-04 9.8896372e-01]]
1/1 [==============================] - 0s 26ms/step
[[0.04394269 0.01896581 0.00185802 0.93523353]]
1/1 [==============================] - 0s 29ms/step
[[2.5369592e-02 9.8035559e-03 8.7987480e-04 9.6394700e-01]]
1/1 [==============================] - 0s 25ms/step
[[2.8757012e-02 1.3480312e-02 7.1095285e-04 9.5705169e-01]]
1/1 [==============================] - 0s 24ms/step
[[1.4754893e-02 5.5699758e-03 7.1669678e-04 9.7895837e-01]]
1/1 [==============================] - 0s 26ms/step
[[1.5949508e-02 6.5227454e-03 9.3079737e-04 9.7659689e-01]]
1/1 [==============================] - 0s 24ms/step
[[0.03388062 0.01665625 0.00180711 0.9476561 ]]
1/1 [==============================] - 

In [2]:
def get_user_choice():
    user_choice = input("Please enter rock (r), paper (p) or scissors (s)")

    if user_choice == "r":
        return "rock"
    elif user_choice == "p":
        return "paper"
    elif user_choice =="s":
        return "scissors"
    else:
        return "invalid"


In [3]:
def get_computer_choice(choice_list):
    import random   
    return random.choice(choice_list)

In [4]:
def who_won(user_choice, computer_choice):
    if user_choice == computer_choice:
        return "The result is a draw"
    elif user_choice == 'rock':
        if computer_choice == 'scissors':
            return "Rock sharpens scissors: you win"
        elif computer_choice == 'paper':
            return "Paper wraps rock: computer wins"
        else:
            return "The computer's selection could not be processed"
    elif user_choice == 'scissors':
        if computer_choice == 'paper':
            return "Scissors cut paper=: you win"
        elif computer_choice == 'rock':
            return "Rock sharpens scissors: computer wins"
        else:
            return "The computer's selection could not be processed"
    elif user_choice == 'paper':
        if computer_choice == 'scissors':
            return "Scissors cut paper=: computer wins"
        elif computer_choice == 'rock':
            return "Rock sharpens scissors: you win"
        else:
            return "The computer's selection could not be processed"
    else:
        return "Your selection could not be processed"

In [5]:
def play_rps():
    rps_list = ['rock', 'paper', 'scissors']
    computer_choice = get_computer_choice(rps_list)
    user_choice = get_user_choice()

    print("You chose", user_choice)
    print("The computer chose", computer_choice)
    print(who_won(user_choice, computer_choice))

In [6]:
play_rps()

You chose rock
The computer chose paper
Paper wraps rock: computer wins
