In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    if prediction[0][0]>0.5:
        print('Rock')
    elif prediction[0][1]>0.5:
        print('Papper')
    elif prediction[0][2]>0.5:
        print('Scissors')
    elif prediction[0][3]>0.5:
        print('Nothing')
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

1/1 [==============================] - 1s 782ms/step
Rock
[[0.58929497 0.00184901 0.09139609 0.31745997]]
1/1 [==============================] - 0s 26ms/step
Nothing
[[0.28073388 0.03211578 0.09054165 0.5966087 ]]
1/1 [==============================] - 0s 30ms/step
Nothing
[[0.0635593  0.01352492 0.11089072 0.81202507]]
1/1 [==============================] - 0s 27ms/step
Nothing
[[0.0635593  0.01352492 0.11089072 0.81202507]]
1/1 [==============================] - 0s 27ms/step
Nothing
[[0.12652794 0.0126633  0.18213028 0.6786785 ]]
1/1 [==============================] - 0s 27ms/step
Nothing
[[0.2157822  0.03102337 0.2025094  0.5506851 ]]
1/1 [==============================] - 0s 34ms/step
Nothing
[[0.2157822  0.03102337 0.2025094  0.5506851 ]]
1/1 [==============================] - 0s 24ms/step
Nothing
[[0.17928353 0.01734511 0.09295073 0.71042067]]
1/1 [==============================] - 0s 25ms/step
Rock
[[0.5265999  0.00330312 0.03987579 0.4302212 ]]
1/1 [============================