In [9]:
import cv2
from keras.models import load_model
import numpy as np
import time
import camera_rps
choice_list = ['Rock', 'Paper', 'Scissors']
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
started= False
next_round=True
countdown=False
counter=0
elapsed=0
round_time=0
message=''
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
computer_wins=[]
user_wins=[]
game_counter=0
game_counter_record=[]
while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    if not started:
        message ='Press a to start'
    if cv2.waitKey(33)==ord('a'):
        game_counter_record.append(game_counter)
        game_counter+=1
        if not started:
            counter=time.time()
            started=True
            countdown=True
    if started:
        elapsed=5-(time.time()-counter)
        b=elapsed
        if elapsed <= -6:
            countdown= False
            message='Press n to play the next round'
            if cv2.waitKey(33)==ord('n'):
                started =False
                elapsed=0
        elif elapsed <=-3:
            if np.unique(user_wins).size==3:
                message=f'You win! The Final goal is {np.unique(user_wins).size}-{np.unique(computer_wins).size}'
            elif np.unique(computer_wins).size==3:
                message=f'Computer wins! The Final goal is {np.unique(computer_wins).size}-{np.unique(user_wins).size}'
            else:
                message=f'you score is {np.unique(user_wins).size}, computer score is {np.unique(computer_wins).size}'
        elif elapsed<=-1:
            countdown= False
            message =f' computer choice is {record_saving[0]}, your choice is {record_saving[1]} {record_saving[2]}'
            if record_saving[2]=='you win':
                user_wins.append(np.max(game_counter_record))
            elif record_saving[2]=='computer wins':
                computer_wins.append(np.max(game_counter_record))
        elif elapsed<=0:
            record_saving=[]
            countdown= False
            computer_choice
            record_saving.append(computer_choice)
            user_choice=camera_rps.get_prediction(prediction)
            record_saving.append(user_choice)
            winner=camera_rps.who_won(user_choice,computer_choice)
            record_saving.append(winner)
        if countdown:
            computer_choice=camera_rps.get_computer_choice(choice_list)
            message=f'Show your hand in{int(elapsed)} seconds'
    cv2.putText(frame,message,(20,20),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0),2)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    print(user_wins)
    print(computer_wins)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()



1/1 [==============================] - 1s 898ms/step
[[2.1208063e-04 5.8394529e-05 3.4169323e-06 9.9972612e-01]]
[]
[]
1/1 [==============================] - 0s 27ms/step
[[5.8902674e-03 1.7784785e-04 9.8010496e-05 9.9383390e-01]]
[]
[]
1/1 [==============================] - 0s 25ms/step
[[1.3720401e-03 8.9450419e-05 2.1434653e-05 9.9851710e-01]]
[]
[]
1/1 [==============================] - 0s 24ms/step
[[9.2275656e-04 7.7947967e-05 1.3623172e-05 9.9898559e-01]]
[]
[]
1/1 [==============================] - 0s 26ms/step
[[9.16513614e-04 8.72145829e-05 1.20490095e-05 9.98984277e-01]]
[]
[]
1/1 [==============================] - 0s 25ms/step
[[2.2319392e-03 1.8917282e-04 2.9935083e-05 9.9754888e-01]]
[]
[]
1/1 [==============================] - 0s 25ms/step
[[5.1935215e-04 6.4059386e-05 8.8873840e-06 9.9940765e-01]]
[]
[]
1/1 [==============================] - 0s 23ms/step
[[1.8229925e-03 1.2673289e-04 3.3074033e-05 9.9801719e-01]]
[]
[]
1/1 [==============================] - 0s 26ms/step

In [ ]:
a=[2,1,0]
b=[]
import numpy as np
np.argmax(a)
b.append(np.argmax(a))
b

In [8]:
import numpy as np
a=np.unique(computer_wins)
a.size
np.unique(computer_wins).size

3

In [7]:


np.unique(user_wins)

array([4])

In [ ]:
            if computer_choice== user_choice:
                user_wins+=1
            elif winner=='computer win':
                computer_wins+=1            
                if elapsed<-3:
                    message='my score {user_wins}, computer score{computer_wins}'   

In [ ]:
message =f' your choice is {user_choice}, computer choice is {computer_choice} {winner}'  

In [ ]:
import camera_rps
camera_rps.who_won('Rock','Scissors')

In [ ]:
import camera_rps
user_wins=0
computer_wins=0
winner=camera_rps.who_won('Paper','Scissors')
if winner=='you win':
     user_wins+=1
     
elif winner=='computer wins':
     computer_wins+=1
print(computer_wins)
print(winner)

In [ ]:
            user_choice=camera_rps.get_prediction(prediction)
            
            computer_choice=camera_rps.get_computer_choice(choice_list)
            message =f'Your choice is{user_choice},computer is{computer_choice}'
            winner=camera_rps.who_won(user_choice,computer_choice)

In [ ]:
b=0






In [ ]:
a=
if a=1:
    a=a+1

In [ ]:
import camera_rps
import cv2
from keras.models import load_model
import numpy as np

model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    prediction = model.predict(data)
    if prediction[0][0]>0.5:
        print('Rock')
    elif prediction[0][1]>0.5:
        print('Papper')
    elif prediction[0][2]>0.5:
        print('Scissors')
    elif prediction[0][3]>0.5:
        print('Nothing')
 

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()